name: Build Debug APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK (assembleDebug)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK (platform & build-tools)
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: '34.0.0'

      - name: Set up Gradle (optional, used if gradlew missing)
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.4'

      - name: Make gradlew executable (if present)
        run: chmod +x ./gradlew || true

      - name: Build Debug APK (use wrapper if present, else system gradle)
        run: |
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug --no-daemon
          else
            gradle assembleDebug --no-daemon
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
